TrainingRecordSystem/TrainingRecordSystemMVC/ViewModels/AddProgramDetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TrainingRecordSystemMVC.ViewModels
{
    public class AddProgramDetailsViewModel
    {
        [Required(ErrorMessage ="Start date is required.")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "End date is required.")]
        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Start time is required.")]
        public string StartTime { get; set; }

        [Required(ErrorMessage = "End time is required.")]
        public string EndTime { get; set; }

        [Required(ErrorMessage = "Mode of preference is required.")]
        public string ModePreference { get; set; }

        public string TargetAudience { get; set; } = string.Empty;

        [Required]
        public int TrainerTopicId { get; set; }
    }
}

TrainingRecordSystem/TrainingRecordSystemMVC/ViewModels/UpdateProgramDetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TrainingRecordSystemMVC.ViewModels
{
    public class UpdateProgramDetailsViewModel
    {
        [Required]
        public int TrainerProgramDetailId { get; set; }

        [Required(ErrorMessage = "Start date is required.")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "End date is required.")]
        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Start time is required.")]
        public string StartTime { get; set; }

        [Required(ErrorMessage = "End time is required.")]
        public string EndTime { get; set; }

        [Required(ErrorMessage = "Mode of preference is required.")]
        public string ModePreference { get; set; }

        public string TargetAudience { get; set; }

        [Required]
        public int TrainerTopicId { get; set; }
    }
}

TrainingRecordSystem/TrainingRecordSystemMVC/Controllers/TrainerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using NuGet.DependencyResolver;
using NuGet.Protocol;
using TrainingRecordSystemMVC.Infrastructure;
using TrainingRecordSystemMVC.ViewModels;

namespace TrainingRecordSystemMVC.Controllers
{
    public class TrainerController : Controller
    {
        private readonly IHttpClientService _httpClientService;

        private readonly IConfiguration _configuration;

        private string endPoint;

        public TrainerController(IHttpClientService httpClientService, IConfiguration configuration)
        {
            _httpClientService = httpClientService;
            _configuration = configuration;
            endPoint = _configuration["EndPoint:CivicaApi"];
        }

        [TrainerAuthorize]

        public IActionResult Index(int page = 1, int pageSize = 4)
        {
          
            var trainerID = User.FindFirst("UserId").Value;
            var apiUrl = $"{endPoint}Trainer/GetAllTrainingTopicbyTrainerId/" + trainerID
                + "?page=" + page
                + "&pageSize=" + pageSize;

            var totalCountApiUrl = $"{endPoint}Trainer/TotalCountofTrainingTopicbyTrainerId/" + trainerID;

            ServiceResponse<int> countResponse = new ServiceResponse<int>();
            ServiceResponse<IEnumerable<TopicByPaginationViewModel>> response = new ServiceResponse<IEnumerable<TopicByPaginationViewModel>>();

            response = _httpClientService.ExecuteApiRequest<ServiceResponse<IEnumerable<TopicByPaginationViewModel>>>
                (apiUrl, HttpMethod.Get, HttpContext.Request);

            countResponse = _httpClientService.ExecuteApiRequest<ServiceResponse<int>>
                (totalCountApiUrl, HttpMethod.Get, HttpContext.Request);

            var totalCount = countResponse.Data;

            var totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

            ViewBag.page = page;
            ViewBag.pageSize = pageSize;
            ViewBag.TotalPages = totalPages;

            if (response.Success)
            {

                return View(response.Data);
            }

            return View(new List<TopicByPaginationViewModel>());

        }


        [HttpGet]
        [TrainerAuthorize]
        public IActionResult AddProgramDetails()
        {
            return View();
        }
        [HttpPost]
        [TrainerAuthorize]
        public IActionResult AddProgramDetails(AddProgramDetailsViewModel addProgramDetailsViewModel)
        {
            var apiUrl = $"{endPoint}Trainer/AddTrainingProgramDetail";

            var response = _httpClientService.PostHttpResponseMessage<AddProgramDetailsViewModel>(apiUrl, addProgramDetailsViewModel, HttpContext.Request);
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var serviceResponse = JsonConvert.DeserializeObject<ServiceResponse<AddProgramDetailsViewModel>>(data);

                if (serviceResponse != null && serviceResponse.Success && serviceResponse.Data != null)
                {
                    return View(serviceResponse.Data);
                }
                else
                {
                    TempData["successMessage"] = serviceResponse?.Message;
                    return RedirectToAction("Index");
                }

            }
            else
            {
                string errorData = response.Content.ReadAsStringAsync().Result;
                var errorResponse = JsonConvert.DeserializeObject<ServiceResponse<AddProgramDetailsViewModel>>(errorData);

                if (errorResponse != null)
                {
                    TempData["errorMessage"] = errorResponse.Message;
                }
                else
                {
                    TempData["errorMessage"] = "Something went wrong, please try after sometime.";
                }

                return View(addProgramDetailsViewModel);
            }
        }

        //------------------Get All Nominated Participants BY Pagination & Sorting--------------------
        [TrainerAuthorize]
        public IActionResult GetNominatedParticipants(int page = 1, int pageSize = 4, string sort_name = "default")
        {
            var apiUrl = $"{endPoint}Trainer/GetAllParticipantsByPaginationSorting"
                + "?page=" + page
                + "&pageSize=" + pageSize
                + "&sort_name=" + sort_name;


            var totalCountApiUrl = $"{endPoint}Trainer/TotalParticipantsCount";
                


            ServiceResponse<int> countResponse = new ServiceResponse<int>();
            ServiceResponse<IEnumerable<GetNominatedParticipateViewModel>> response = new ServiceResponse<IEnumerable<GetNominatedParticipateViewModel>>();

            response = _httpClientService.ExecuteApiRequest<ServiceResponse<IEnumerable<GetNominatedParticipateViewModel>>>
                (apiUrl, HttpMethod.Get, HttpContext.Request);

            countResponse = _httpClientService.ExecuteApiRequest<ServiceResponse<int>>
                (totalCountApiUrl, HttpMethod.Get, HttpContext.Request);

            var totalCount = countResponse.Data;

            var totalPages = (int)Math.Ceiling((double)totalCount / pageSize);


            ViewBag.page = page;
            ViewBag.pageSize = pageSize;
            ViewBag.TotalPages = totalPages;
            ViewBag.sort_name = sort_name;
            

            if (response.Success)
            {

                return View(response.Data);
            }

            return View(new List<GetNominatedParticipateViewModel>());
        }

        //----Program detials----
        [TrainerAuthorize]
        public IActionResult GetProgramDetails(int id)
        {
            var trainerID = User.FindFirst("UserId").Value;
            var apiUrl = $"{endPoint}Trainer/GetAllTrainingProgramDetails?userId=" + trainerID + "&topicId=" + id;
            var response = _httpClientService.GetHttpResponseMessage<TrainingProgramDetailsViewModel>(apiUrl, HttpContext.Request);

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var serviceResponse = JsonConvert.DeserializeObject<ServiceResponse<TrainingProgramDetailsViewModel>>(data);

                if (serviceResponse != null && serviceResponse.Success && serviceResponse.Data != null)
                {
                    return View(serviceResponse.Data);
                }
                else
                {
                    TempData["errorMessage"] = serviceResponse?.Message;
                    return RedirectToAction("Index");
                }

            }
            else
            {
                string errorData = response.Content.ReadAsStringAsync().Result;
                var errorResponse = JsonConvert.DeserializeObject<ServiceResponse<TrainingProgramDetailsViewModel>>(errorData);

                if (errorResponse != null)
                {
                    TempData["errorMessage"] = errorResponse.Message;
                }
                else
                {
                    TempData["errorMessage"] = "Something went wrong. Please try after sometime.";
                }
                return RedirectToAction("Index");
            }


        }

        [HttpGet]
        [TrainerAuthorize]
        public IActionResult UpdateProgramDetails(int topicId)
        {
         
            var trainerID = User.FindFirst("UserId").Value;
            var apiUrl = $"{endPoint}Trainer/GetAllTrainingProgramDetails?userId=" + trainerID + "&topicId=" + topicId;
            var response = _httpClientService.GetHttpResponseMessage<TrainingProgramDetailsViewModel>(apiUrl, HttpContext.Request);

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var serviceResponse = JsonConvert.DeserializeObject<ServiceResponse<TrainingProgramDetailsViewModel>>(data);

                if (serviceResponse != null && serviceResponse.Success && serviceResponse.Data != null)
                {
                    var details = serviceResponse.Data;
                    UpdateProgramDetailsViewModel viewModel = new UpdateProgramDetailsViewModel();
                    viewModel.TrainerProgramDetailId = details.TrainerProgramDetailId;
                    viewModel.StartDate = details.StartDate;
                    viewModel.EndDate = details.EndDate;
                    viewModel.StartTime = details.StartTime.Hour.ToString() + ":00";
                    viewModel.EndTime = details.EndTime.Hour.ToString() + ":00";
                    viewModel.ModePreference = details.ModePreference;
                    viewModel.TargetAudience = details.TargetAudience;
                    viewModel.TrainerTopicId = details.TrainerTopicId;
                    return View(viewModel);
                }
                else
                {
                    TempData["errorMessage"] = serviceResponse.Message;
                    return RedirectToAction("Index");
                }

            }
            else
            {
                string errorData = response.Content.ReadAsStringAsync().Result;
                var errorResponse = JsonConvert.DeserializeObject<ServiceResponse<TrainingProgramDetailsViewModel>>(errorData);

                if (errorResponse != null)
                {
                    TempData["errorMessage"] = errorResponse.Message;
                }
                else
                {
                    TempData["errorMessage"] = "Something went wrong. Please try after sometime.";
                }
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [TrainerAuthorize]
        public IActionResult UpdateProgramDetails(UpdateProgramDetailsViewModel viewModel)
        {

TrainingRecordSystem/TrainingRecordSystemMVC/Views/Trainer/AddProgramDetails.cshtml
@using TrainingRecordSystemMVC.ViewModels
@model AddProgramDetailsViewModel

<div class="container">
    <h2 class="custom-heading text-center my-3">Add Training Program Details</h2>

    <form asp-action="AddProgramDetails" method="post" class="needs-validation" novalidate>
        <div class="row justify-content-center">
            <div class="col-md-6 mb-3">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row mb-3">

                            <div class="col-md-6 form-group">
                                <label asp-for="StartDate" class="form-label">Start Date</label>
                                <input type="date" class="form-control" id="StartDate" name="StartDate">
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                                    
                            </div>

                            <div class="col-md-6">
                                <label asp-for="EndDate" class="form-label">End Date</label>
                                <input type="date" class="form-control" id="EndDate" name="EndDate" >
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-4">
                                <label asp-for="StartTime" class="form-label">Start Time</label>
                                <select class="form-select" id="StartTime" name="StartTime" required>
                                    <option value="" selected disabled>- Select time --</option>
                                  @*   <option value="time1">Time 1</option>
                                    <option value="time2">Time 2</option> *@
                                    <!-- Add options dynamically if needed -->
                                </select>
                                <span asp-validation-for="StartTime" class="text-danger"></span>
                            </div>
                            <div class="col-md-4">
                                <label asp-for="EndTime" class="form-label">End Time</label>
                                <select class="form-select" id="EndTime" name="EndTime" required>
                                    <option value="" selected disabled>- Select time --</option>
                                @*     <option value="time1">Time 1</option>
                                    <option value="time2">Time 2</option> *@
                                    <!-- Add options dynamically if needed -->
                                </select>
                                <span asp-validation-for="EndTime" class="text-danger"></span>
                            </div>

                            <div class="col-md-4">
                                <label class="form-label">Duration</label>
                                <input class="form-control" type="text" id="Duration" name="Duration" readonly>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label asp-for="ModePreference" class="form-label">Mode Preference</label>
                                <select class="form-select" id="ModePreference" name="ModePreference" required>
                                    <option value="" selected disabled>-- Select mode --</option>
                                    <option value="offline">Offline</option>
                                    <option value="online">Online</option>
                                    <option value="hybrid">Hybrid</option>
                                </select>
                                <span asp-validation-for="ModePreference" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="TargetAudience" class="form-label">Target Audience</label>
                                <textarea class="form-control" id="TargetAudience" name="TargetAudience" placeholder="Additional notes"></textarea>
                            </div>
                        </div>

                        <div class="d-flex justify-content-between">
                            <a href="/TrainingTopics" class="btn btn-outline-danger me-2"><i class="fas fa-arrow-left"></i></a>
                            <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        </div>

                        <div>
                            <input asp-for="TrainerTopicId" id="TrainerTopicId" type="hidden" name="TrainerTopicId" value=0 />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    function populateTimesDropdown(selectId) {
        var select = document.getElementById(selectId);

        select.innerHTML = '';
        
        var defaultOption = document.createElement('option');
        defaultOption.value = '';
        defaultOption.text = '- Select time --';
        defaultOption.disabled = true;
        defaultOption.selected = true;
        select.appendChild(defaultOption);

        
        for (var hour = 10; hour < 20; hour++) {
            var hourStr = (hour < 10) ? '0' + hour : '' + hour; 
            var option = document.createElement('option');
            option.value = hourStr + ':00';
            option.text = hourStr + ':00';
            select.appendChild(option);
        }

        select.addEventListener('change', function () {
            calculateDuration();
        });
    }

    
    populateTimesDropdown('StartTime');

    populateTimesDropdown('EndTime');

    
    function calculateDuration() {
        var startTimeSelect = document.getElementById('StartTime');
        var endTimeSelect = document.getElementById('EndTime');
        var durationInput = document.getElementById('Duration');

        var startTime = startTimeSelect.value;
        var endTime = endTimeSelect.value;

        // Check if both start time and end time are selected
        if (startTime && endTime) {
           
            var start = new Date('2000-01-01T' + startTime + ':00');
            var end = new Date('2000-01-01T' + endTime + ':00');

            var difference = end - start;

            if(difference <= 0 )
            {
                difference = 0;
                alert("please choose appropriate time")
                return;
            }

            var hours = Math.floor(difference / 3600000);
            var minutes = Math.round((difference % 3600000) / 60000);

            var duration = hours.toString().padStart(2, '0') + ':' + minutes.toString().padStart(2, '0');

            durationInput.value = duration;
        } else {
            durationInput.value = '';
        }
    }

    //For disable previous dates
    function setMinimumDate() {
        var today = new Date();
        var dd = String(today.getDate()).padStart(2, '0');
        var mm = String(today.getMonth() + 1).padStart(2, '0');
        var yyyy = today.getFullYear();

        var minDate = yyyy + '-' + mm + '-' + dd;

        document.getElementById('StartDate').min = minDate;
        document.getElementById('EndDate').min = minDate;
    }

    setMinimumDate();

    function getTrainerTopicId(){
        var currentUrl = window.location.href;
        var id = currentUrl.substring(currentUrl.lastIndexOf('/') + 1);
        console.log(id);
        var idInt = parseInt(id, 10);
        console.log(idInt);
        document.getElementById('TrainerTopicId').value = idInt;
    }

    getTrainerTopicId();
</script>

TrainingRecordSystem/TrainingRecordSystemMVC/Views/Trainer/GetProgramDetails.cshtml
@using TrainingRecordSystemMVC.ViewModels
@model TrainingProgramDetailsViewModel


    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card shadow-sm mb-4 mt-5">
                    <div class="card-body">
                        <h2 class="card-title mb-2"><i class="fas fa-info-circle"></i> Training Topic Details</h2>
                    <p class="card-text mb-2"><i class="fas fa-calendar-alt"></i> Start Date: @Model.StartDate.ToString("dd/MM/yyyy")</p>
                    <p class="card-text mb-2"><i class="fas fa-calendar-alt"></i> End Date: @Model.EndDate.ToString("dd/MM/yyyy")</p>
                        <div class="final-price mb-2"><i class="fas fa-clock"></i> Time: @Model.StartTime.ToShortTimeString() to @Model.EndTime.ToShortTimeString()</div>
                        <div class="price mb-2"><i class="fas fa-chalkboard-teacher"></i> Mode: @Model.ModePreference</div>
                        <div class="final-price mb-2"><i class="fas fa-hourglass-half"></i> Duration: @Model.Duration hrs/day</div>
                        <div class="final-price mb-2"><i class="fas fa-users"></i> Target Audience: @Model.TargetAudience</div>

                       @*  <div>
                            <a asp-action="Index" class="btn civicaBtn btn-sm">
                                <i class="fas fa-list"></i> Back to list
                            </a>
                            <a asp-action="UpdateProgramDetails" asp-route-topicid="@Model.TrainerTopic.TopicId" class="btn civicaBtn btn-sm mx-2" id="updateLink">
                                <i class="fas fa-edit"></i> Update details
                            </a>
                        </div> *@

                    <div class="d-flex justify-content-between mt-3">
                        <a type="button" class="btn btn-outline-danger me-2" asp-action="Index"><i class="fas fa-arrow-left"></i></a>
                        <a type="button" value="Submit" class="btn btn-primary btn-block" style="background-color:#00b4c1" asp-action="UpdateProgramDetails" asp-route-topicid="@Model.TrainerTopic.TopicId" id="updateLink">Update Details</a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
    .btn-block {
        background-color: #009CA6;
        width: 100%;
    }
    </style>

TrainingRecordSystem/TrainingRecordSystemMVC/Views/Trainer/Index.cshtml
@using TrainingRecordSystemMVC.ViewModels
@model List<TopicByPaginationViewModel>

<h1 class="custom-heading text-center my-3">Assigned Topics</h1>

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="text-light" style="background-color:#00b4c1">Topic Name</th>
                <th class="text-light" style="background-color:#00b4c1">Job Role </th>
                <th class="text-light" style="background-color:#00b4c1">Action</th>
            </tr>
        </thead>
        @if (Model == null || Model.Count == 0)
        {
            <tbody>
            <td colspan="6" class="text-center">
                No Record Found!
            </td>
            </tbody>
        }
        else
        {
            <tbody>
                @foreach (var topic in Model)
                {
                    <tr>

                        <td>@topic.Topic.TopicName</td>
                        <td>@topic.Job.JobName</td>
                    
                        @if(topic.isTrainingScheduled)
                        {
                            
                        <td>
                                <a asp-controller="Trainer" asp-action="GetProgramDetails" asp-route-id="@topic.TopicId" class="btn btn-outline-dark">Topic Detail</a>
                            </td>
                        }
                        else
                        {
                            <td>
                            <a asp-controller="Trainer" asp-action="AddProgramDetails" asp-route-id="@topic.TrainerTopicId" class="btn btn-outline-dark">Add Detail</a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        }

    </table>

    <!-- Pagination -->
    <div class="row mb-3 align-items-center">
        <div class="col-sm-3">
            <!-- Page Size Dropdown -->
            <div class="page-size-container">

                <select id="pageSize" class="form-select" value="@ViewBag.pageSize" onchange="changePage(1, this.value)">
                    <option value="2">2</option>
                    <option value="4">4</option>
                    <option value="6">6</option>
                </select>
            </div>
        </div>
        <div class="col-sm-6 d-flex justify-content-center">
            <!-- Pagination controls -->

            <ul class="pagination">
                <!-- Previous Button -->
                <li class="page-item @(ViewBag.page == 1 ? "disabled" : "")">
                    <a class="page-link" href="/Trainer/Index?page=@(ViewBag.page - 1)&pageSize=@ViewBag.pageSize">Previous</a>
                </li>
                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                {
                    <li class="page-item @(i == ViewBag.page ? "active" : "")">

                        <a class="page-link" href="/Trainer/Index?page=@i&pageSize=@ViewBag.pageSize">@i</a>
                    </li>
                }
                <!-- Next Button -->
                <li class="page-item @(ViewBag.page == ViewBag.TotalPages ? "disabled" : "")">
                    <a class="page-link" href="/Trainer/Index?page=@(ViewBag.page + 1)&pageSize=@ViewBag.pageSize">Next</a>

                </li>

            </ul>

        </div>

        @* <div class="col-sm-3 d-flex justify-content-end">
            <a asp-action="Create" class="btn btn-dark" style="background-color:#00b4c1"><i class="fa fa-user-plus"></i></a>
        </div> *@





    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var currentPageSize = @(ViewBag.PageSize); // Get current page size from ViewBag
        var pageSizeDropdown = document.getElementById("pageSize");
        // Set selected option based on current page size
        for (var i = 0; i < pageSizeDropdown.options.length; i++) {
            if (pageSizeDropdown.options[i].value === currentPageSize.toString()) {
                pageSizeDropdown.selectedIndex = i;
                break;
            }
        }



        var rows = document.querySelectorAll('td[data-href]');
        rows.forEach(function (row) {
            row.addEventListener('click', function () {
                window.location.href = row.getAttribute('data-href');
            });
        });
    });

    function changePage(page, pageSize) {

        window.location.href = "/Trainer/Index"
            + "?page=" + page
            + "&pageSize=" + pageSize;

    }
</script>

<style>

    /* Custom styles for the page size dropdown */
    #pageSize {
        width: 80px;
        display: inline-block;
    }

    /* Custom pagination styles */
    .pagination {
        margin-top: 20px;
    }

        .pagination .page-item.active .page-link {
            background-color: #00b4c1;
            border-color: #00b4c1;
            color: black; /* Set the text color to black for active page link */
        }

        .pagination .page-item .page-link {
            color: #00b4c1;
        }

        .pagination .page-item.disabled .page-link {
            color: #6c757d;
            pointer-events: none;
            cursor: default;
        }

    /* Additional margin for the page size label */
    label[for="pageSize"] {
        margin-right: 10px;
    }

    .page-size-container {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
        font-family: 'Arial', sans-serif;
    }

        /* Styling the label */
        .page-size-container label {
            margin-right: 10px;
            font-weight: bold;
            font-size: 1.1em;
        }

    /* Custom styles for the dropdown */
    #pageSize {
        width: 100px;
        padding: 5px 10px;
        font-size: 1em;
        border: 2px solid #00b4c1;
        border-radius: 5px;
        color: #00b4c1;
        background-color: #f8f9fa;
        transition: all 0.3s ease;
    }

        #pageSize:hover {
            border-color: #00b4c1;
            color: #00b4c1;
        }



    /* Additional margin for the page size label */
    label[for="pageSize"] {
        margin-right: 10px;
    }

    /* Positioning and styling the loader overlay */
    .loader-overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(255, 255, 255, 0.8); /* Semi-transparent background */
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 1000; /* Ensure it's on top */
    }

    /* Centering the loader image */
    .loader-image {
        width: 50px;
        height: 50px;
    }

    .table {
        border-collapse: separate;
        border-spacing: 10px; /* Adjust the spacing as needed */
    }

        .table th,
        .table td {
            padding: 10px; /* Add padding if needed for content */
            text-align: center;
        }

    .custom-thead {
        background-color: #00b4c1;
    }

    .form-label {
        font-weight: bold;
        margin-bottom: 0.5rem;
    }

    .form-select {
        width: 100%;
        padding: 0.375rem 1.75rem 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

        .form-select:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }

    .pagination {
        margin: 1rem;
    }

    .custom-heading {
        margin-top: 15px;
        font-size: 2rem; /* Adjust the size as needed */
        font-weight: bold; /* Makes the text bold */
        color: #000000; /* Custom color */
        text-align: center; /* Center the text */
    }

</style>

TrainingRecordSystem/TrainingRecordSystemMVC/Views/Trainer/TrainingProgram.cshtml
<h1>
    Helloo
</h1>